"""add_trade_data_tables

Revision ID: 07614f34cf47
Revises: 414303a37a97
Create Date: 2026-04-07 01:04:32.371914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '07614f34cf47'
down_revision: Union[str, None] = '414303a37a97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_summary',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('total_buy_count', sa.Integer(), nullable=False),
    sa.Column('total_sell_count', sa.Integer(), nullable=False),
    sa.Column('total_profit_loss', sa.Integer(), nullable=False),
    sa.Column('win_rate', sa.Float(), nullable=False),
    sa.Column('stop_loss_count', sa.Integer(), nullable=False),
    sa.Column('take_profit_count', sa.Integer(), nullable=False),
    sa.Column('strategy_sell_count', sa.Integer(), nullable=False),
    sa.Column('screening_count', sa.Integer(), nullable=False),
    sa.Column('screening_conversion_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('cycle_count', sa.Integer(), nullable=False),
    sa.Column('summary_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_summary_report_date'), 'daily_summary', ['report_date'], unique=True)
    op.create_table('screening_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stock_code', sa.String(length=20), nullable=False),
    sa.Column('stock_name', sa.String(length=100), nullable=False),
    sa.Column('screening_rank', sa.Integer(), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('price_change_pct', sa.Float(), nullable=False),
    sa.Column('converted_to_trade', sa.Boolean(), nullable=False),
    sa.Column('cycle_number', sa.Integer(), nullable=False),
    sa.Column('screened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_screening_results_stock_code'), 'screening_results', ['stock_code'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stock_code', sa.String(length=20), nullable=False),
    sa.Column('stock_name', sa.String(length=100), nullable=False),
    sa.Column('signal_type', sa.String(length=50), nullable=False),
    sa.Column('signal_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('action_taken', sa.Boolean(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_signal_type'), 'signals', ['signal_type'], unique=False)
    op.create_index(op.f('ix_signals_stock_code'), 'signals', ['stock_code'], unique=False)
    op.create_table('system_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('metric_type', sa.String(length=50), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_metrics_metric_type'), 'system_metrics', ['metric_type'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stock_code', sa.String(length=20), nullable=False),
    sa.Column('stock_name', sa.String(length=100), nullable=False),
    sa.Column('trade_type', sa.Enum('BUY', 'SELL', name='trade_type_enum'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Integer(), nullable=False),
    sa.Column('sell_reason', sa.Enum('STOP_LOSS', 'TAKE_PROFIT', 'STRATEGY', 'MANUAL', name='sell_reason_enum'), nullable=True),
    sa.Column('signal_type', sa.String(length=50), nullable=True),
    sa.Column('profit_loss_pct', sa.Float(), nullable=True),
    sa.Column('profit_loss_amount', sa.Integer(), nullable=True),
    sa.Column('cycle_number', sa.Integer(), nullable=False),
    sa.Column('traded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_stock_code'), 'trades', ['stock_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_stock_code'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_system_metrics_metric_type'), table_name='system_metrics')
    op.drop_table('system_metrics')
    op.drop_index(op.f('ix_signals_stock_code'), table_name='signals')
    op.drop_index(op.f('ix_signals_signal_type'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_screening_results_stock_code'), table_name='screening_results')
    op.drop_table('screening_results')
    op.drop_index(op.f('ix_daily_summary_report_date'), table_name='daily_summary')
    op.drop_table('daily_summary')
    # ### end Alembic commands ###
