"""add buy_reason to trades

Revision ID: 499487c40196
Revises: 07614f34cf47
Create Date: 2026-04-08 00:54:49.331546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '499487c40196'
down_revision: Union[str, None] = '07614f34cf47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    buy_reason_enum = sa.Enum('GOLDEN_CROSS', 'RSI_OVERSOLD', 'ENSEMBLE', 'MANUAL', name='buy_reason_enum')
    buy_reason_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('trades', sa.Column('buy_reason', buy_reason_enum, nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'buy_reason')
    sa.Enum(name='buy_reason_enum').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
