"""add event_logs table

Revision ID: 6983b5db290d
Revises: 7be42bd70188
Create Date: 2026-04-03 17:29:38.000451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6983b5db290d'
down_revision: Union[str, None] = '7be42bd70188'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('level', sa.Enum('INFO', 'WARNING', 'ERROR', name='event_level_enum'), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_logs_category'), 'event_logs', ['category'], unique=False)
    op.create_index(op.f('ix_event_logs_timestamp'), 'event_logs', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_logs_timestamp'), table_name='event_logs')
    op.drop_index(op.f('ix_event_logs_category'), table_name='event_logs')
    op.drop_table('event_logs')
    # ### end Alembic commands ###
