"""add implementation_logs table

Revision ID: dcad1efe8855
Revises: 702dbb24bf59
Create Date: 2026-04-27 23:48:01.123095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dcad1efe8855'
down_revision: Union[str, None] = '702dbb24bf59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('implementation_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('category', sa.Enum('BUG_FIX', 'REFACTOR', 'PARAM_TUNING', 'FEATURE', 'ENHANCEMENT', 'PERFORMANCE', 'DOCS', 'CONFIG', name='impl_category_enum'), nullable=False),
    sa.Column('proposal_path', sa.String(length=300), nullable=True),
    sa.Column('changed_files', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('verification', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('background', sa.Text(), nullable=True),
    sa.Column('expected_effect', sa.Text(), nullable=True),
    sa.Column('implemented_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('implementation_logs')
    sa.Enum('BUG_FIX', 'REFACTOR', 'PARAM_TUNING', 'FEATURE', 'ENHANCEMENT',
            'PERFORMANCE', 'DOCS', 'CONFIG', name='impl_category_enum').drop(op.get_bind())
    # ### end Alembic commands ###
